name: Deploy Project
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm ci
        working-directory: ./gh-action-react-demo
      - name: Run tests
        run: npm test
        working-directory: ./gh-action-react-demo
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm ci
        working-directory: ./gh-action-react-demo
      - name: Build projecy
        run: npm run build
        working-directory: ./gh-action-react-demo
      - name: Deploy
        run: echo "Deploying..."
